# Generated by Django 3.0.4 on 2020-11-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20201110_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puesto',
            name='nombre_bodega',
        ),
        migrations.RemoveField(
            model_name='tipo_contrato',
            name='nombre_bodega',
        ),
        migrations.AddField(
            model_name='puesto',
            name='puesto',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='puesto'),
        ),
        migrations.AddField(
            model_name='tipo_contrato',
            name='tipo_contrato',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='tipo_contrato'),
        ),
    ]
