# Generated by Django 3.0.4 on 2020-11-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20201110_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='dpi',
            field=models.CharField(max_length=15, unique=True, verbose_name='DPI'),
        ),
    ]
